### ISSUE TITLE
Plugin fails to build with Godot 4.2+ due to method binding API incompatibility

### ISSUE THREAD

**Issue by k3rps** [meshula/usd-godot#4]
Environment:

- Windows 11, MSVC 2022 (19.44)
- Godot 4.4-stable source
- godot-cpp 4.2 and 4.4 branch (built separately)
- USD built successfully with minimal configuration
- 

Issue:
Build fails with method binding errors across all plugin source files:
```
error C2440: 'reinterpret_cast': cannot convert from 'void (__cdecl godot::UsdExportSettings::* )(bool)' to 'void (__cdecl godot::_gde_UnexistingClass::* )(bool)'
error C2512: 'godot::MethodBindT<bool>::MethodBindT': no appropriate default constructor available

Pointers to members have different representations; cannot cast between them
```

**Steps taken:**

1. Built godot-cpp 4.2 separately using SCons
2. Modified CMakeLists.txt to use hardcoded godot-cpp paths (as suggested in similar issues)
3. Tested with both Godot 4.2-stable and 4.4-stable sources
4. USD and dependencies build successfully

**Root cause:**
The plugin's method binding code appears incompatible with current Godot 4.x API. The _gde_UnexistingClass errors suggest the ClassDB::bind_method calls need updating for the current GDExtension API.

**Request:**
Could the plugin be updated to build with latest?

**Comment by meshula** [comment]
Hi @k3rps ~ should be good to go now, sorry for a late response.

**Comment by meshula** [comment]
Closing this out ~ working for me in 4.5+

**Comment by meshula** [comment]
(feel free to file new issues if you encounter problems)
